"""mirror.py event plug-in that generates rsyncd.conf and rsyncd.secrets.

Reads its own configuration from rsync.json located next to mirror.py's
config.json (mirror.config.CONFIG_PATH.parent / "rsync.json"), and regenerates
both rsyncd files when the daemon starts and on every config reload.
"""
from __future__ import annotations

import json
import logging
import os
import re
import stat
import tempfile
import threading
from pathlib import Path
from typing import Any, Iterable

import mirror
import mirror.config
import mirror.event
import mirror.plugin

NAME = "rsync-server"
RSYNC_CONFIG_FILENAME = "rsync.json"
CONF_HEADER = "# WARNING: DO NOT EDIT!! Generated by the mirror.py rsync-server plugin."
PRIVATE_COMMENT_TEMPLATE = "private module for {name} without connection limits for authorized mirrors"
DEFAULT_PRIVATE_MODULES: dict[str, Any] = {
    "enabled": True,
    "auth_users": "*",
    "list": False,
    "lock_file": "/var/run/rsyncd-private.lock",
}
DEFAULT_RSYNCD_CONF = "/etc/rsyncd.conf"
DEFAULT_SECRETS_FILE = "/etc/rsyncd.secrets"
MODULE_NAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._+-]*$")

log = logging.getLogger("mirror")
_generate_lock = threading.Lock()

# --- Config layer ---

_ALLOWED_TOP_LEVEL_KEYS = frozenset({"rsyncd_conf", "secrets_file", "users", "global", "private_modules"})
_ALLOWED_PRIVATE_MODULES_KEYS = frozenset({"enabled", "auth_users", "list", "lock_file"})


def resolve_rsync_config_path() -> Path:
    """Return the expected path to rsync.json next to mirror.py's config.json.

    Args:
        (none)

    Return:
        path(Path): mirror.config.CONFIG_PATH.parent / RSYNC_CONFIG_FILENAME.
    """
    return mirror.config.CONFIG_PATH.parent / RSYNC_CONFIG_FILENAME


def load_rsync_config(path: Path) -> dict:
    """Read, parse, and validate the rsync.json configuration file.

    Args:
        path(Path): Filesystem path to the rsync.json file.

    Return:
        config(dict): Normalized configuration dict with all keys present.

    Raises:
        ValueError: If the file cannot be read, contains invalid JSON, or
            fails validation. The message includes the path but never file contents.
    """
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise ValueError(f"Cannot read rsync config at {path}: {exc}") from exc

    try:
        raw = json.loads(text)
    except json.JSONDecodeError as exc:
        raise ValueError(f"Invalid JSON in rsync config at {path}: {exc}") from exc

    return validate_rsync_config(raw)


def _is_control_char(ch: str) -> bool:
    """Return True if ch is a C0 (ord < 32), DEL (0x7f), or C1 (0x80-0x9f) control character."""
    code = ord(ch)
    return code < 32 or 0x7F <= code <= 0x9F


def _has_control_chars(value: str) -> bool:
    """Return True if value contains any C0, DEL, or C1 control character."""
    return any(_is_control_char(ch) for ch in value)


def _validate_absolute_clean_path(value: object, field: str) -> str:
    """Validate that value is a str, absolute path, and contains no control chars.

    Args:
        value(object): The value to check.
        field(str): Field name for error messages.

    Return:
        path(str): The validated path string.
    """
    if not isinstance(value, str):
        raise ValueError(f"{field!r} must be a str, got {type(value).__name__}")
    if not os.path.isabs(value):
        raise ValueError(f"{field!r} must be an absolute path, got {value!r}")
    if _has_control_chars(value):
        raise ValueError(f"{field!r} must not contain control characters")
    return value


def validate_rsync_config(raw: dict) -> dict:
    """Validate and normalize a parsed rsync.json dict.

    Applies defaults for all optional keys, rejects unknown keys and any
    value that could enable injection into rsyncd.conf.

    Args:
        raw(dict): Parsed JSON object from rsync.json.

    Return:
        config(dict): Normalized dict with keys: rsyncd_conf, secrets_file,
            users, global, private_modules. All have validated values and
            defaults applied where keys were absent.

    Raises:
        ValueError: On any structural or content violation.
    """
    if not isinstance(raw, dict):
        raise ValueError(f"rsync.json root must be a dict, got {type(raw).__name__}")

    for key in raw:
        if key not in _ALLOWED_TOP_LEVEL_KEYS:
            raise ValueError(f"Unknown key in rsync.json: {key!r}")

    rsyncd_conf = _validate_absolute_clean_path(
        raw.get("rsyncd_conf", DEFAULT_RSYNCD_CONF), "rsyncd_conf"
    )
    secrets_file = _validate_absolute_clean_path(
        raw.get("secrets_file", DEFAULT_SECRETS_FILE), "secrets_file"
    )

    users = raw.get("users", {})
    if not isinstance(users, dict):
        raise ValueError(f"'users' must be a dict, got {type(users).__name__}")
    validate_users(users)

    global_params = raw.get("global", {})
    if not isinstance(global_params, dict):
        raise ValueError(f"'global' must be a dict, got {type(global_params).__name__}")
    _validate_global_params(global_params)

    private_modules_input = raw.get("private_modules", {})
    if not isinstance(private_modules_input, dict):
        raise ValueError(f"'private_modules' must be a dict, got {type(private_modules_input).__name__}")
    private_modules = _validate_private_modules(private_modules_input)

    return {
        "rsyncd_conf": rsyncd_conf,
        "secrets_file": secrets_file,
        "users": users,
        "global": global_params,
        "private_modules": private_modules,
    }


def _validate_global_params(global_params: dict) -> None:
    """Validate all keys and values in the global rsyncd parameter dict."""
    for key, value in global_params.items():
        if not isinstance(key, str) or not key:
            raise ValueError(f"'global' keys must be non-empty strings, got {key!r}")
        if _has_control_chars(key):
            raise ValueError(f"'global' key {key!r} must not contain control characters")
        if "=" in key:
            raise ValueError(f"'global' key {key!r} must not contain '='")
        if key.lstrip().startswith("["):
            raise ValueError(f"'global' key {key!r} must not start with '['")
        if key.strip().lower() == "secrets file":
            raise ValueError(
                f"'global' key {key!r} is reserved; use the top-level 'secrets_file' key instead"
            )
        if not isinstance(value, (str, int, bool)):
            raise ValueError(
                f"'global' value for key {key!r} must be str, int, or bool, got {type(value).__name__}"
            )
        if isinstance(value, str) and _has_control_chars(value):
            raise ValueError(f"'global' value for key {key!r} must not contain control characters")


def _validate_private_modules(provided: dict) -> dict:
    """Validate private_modules overrides and merge with defaults.

    Args:
        provided(dict): Partial or full private_modules dict from rsync.json.

    Return:
        merged(dict): Defaults merged with validated provided values.
    """
    for key in provided:
        if key not in _ALLOWED_PRIVATE_MODULES_KEYS:
            raise ValueError(f"Unknown key in 'private_modules': {key!r}")

    merged = dict(DEFAULT_PRIVATE_MODULES)
    merged.update(provided)

    if not isinstance(merged["enabled"], bool):
        raise ValueError(f"'private_modules.enabled' must be bool, got {type(merged['enabled']).__name__}")
    if not isinstance(merged["list"], bool):
        raise ValueError(f"'private_modules.list' must be bool, got {type(merged['list']).__name__}")

    auth_users = merged["auth_users"]
    if not isinstance(auth_users, str):
        raise ValueError(f"'private_modules.auth_users' must be str, got {type(auth_users).__name__}")
    if _has_control_chars(auth_users):
        raise ValueError("'private_modules.auth_users' must not contain control characters")

    _validate_absolute_clean_path(merged["lock_file"], "private_modules.lock_file")

    return merged


def validate_users(users: dict) -> None:
    """Validate every username/password entry in the users dict.

    Args:
        users(dict): Mapping of username to password strings from rsync.json.

    Return:
        None

    Raises:
        ValueError: If any username is empty, contains ':' / whitespace /
            control characters, or starts with '@' or '#'; or if any password
            is not a non-empty string or contains any control character
            (including CR/LF/TAB/DEL/C1). The message may name the offending
            username but never contains the password value.
    """
    for username, password in users.items():
        if not isinstance(username, str) or not username:
            raise ValueError(f"Username must be a non-empty string, got {username!r}")
        if ":" in username:
            raise ValueError(f"Username {username!r} must not contain ':'")
        if any(ch.isspace() for ch in username):
            raise ValueError(f"Username {username!r} must not contain whitespace")
        if _has_control_chars(username):
            raise ValueError(f"Username {username!r} must not contain control characters")
        if username[0] in ("@", "#"):
            raise ValueError(f"Username {username!r} must not start with '@' or '#'")

        if not isinstance(password, str) or not password:
            raise ValueError(f"Invalid password for user {username!r}: must be a non-empty string")
        if _has_control_chars(password):
            raise ValueError(f"Invalid password for user {username!r}: must not contain control characters")


def check_config_permissions(path: Path) -> None:
    """Warn if rsync.json is readable by group or other.

    The file holds plaintext passwords, so group/other read access is a
    security concern. This function only logs a warning; it never raises and
    never logs the file contents.

    Args:
        path(Path): Filesystem path to the rsync.json file.

    Return:
        None
    """
    try:
        result = os.stat(path)
        if result.st_mode & 0o077:
            log.warning(
                "rsync.json at %s is group/other-readable; recommend chmod 600 "
                "as it contains plaintext passwords",
                path,
            )
    except OSError as exc:
        log.debug("Could not stat rsync.json at %s: %s", path, exc)


# --- Pure text builders ---


def validate_module_name(name: str) -> bool:
    """Return True iff name is a valid rsyncd module name.

    A valid name must match MODULE_NAME_RE and must not equal "global"
    case-insensitively (reserved section name in rsync >= 3.2).

    Args:
        name(str): The candidate module name to validate.

    Return:
        valid(bool): True if name passes all checks, False otherwise.
    """
    if not isinstance(name, str):
        return False
    if not MODULE_NAME_RE.match(name):
        return False
    if name.lower() == "global":
        return False
    return True


def sanitize_comment_value(value: str) -> str:
    """Strip control characters and surrounding whitespace from value.

    rsyncd.conf has no value escaping, so a newline in a comment value
    would inject a new config line. This function removes all characters
    with ord < 32 and strips leading/trailing whitespace.

    Args:
        value(str): The raw string to sanitize (e.g. pkg.settings.src).

    Return:
        cleaned(str): Single-line string with control chars removed and
            surrounding whitespace stripped.
    """
    cleaned = "".join(ch for ch in value if not _is_control_char(ch))
    return cleaned.strip()


def format_param(key: str, value: object) -> str:
    """Render a single rsyncd.conf parameter line as 'key = value'.

    Booleans are rendered as lowercase 'true' or 'false'. All other types
    are converted via str(). Control characters are stripped from the
    rendered value as defense in depth.

    Args:
        key(str): The rsyncd parameter name (e.g. 'max connections').
        value(object): The parameter value. bool, int, or str.

    Return:
        line(str): A 'key = value' string with no indentation or trailing
            newline.
    """
    if isinstance(value, bool):
        rendered = "true" if value else "false"
    else:
        rendered = str(value)
    rendered = "".join(ch for ch in rendered if not _is_control_char(ch))
    return f"{key} = {rendered}"


def select_visible_packages(packages: Iterable) -> list:
    """Filter and sort packages for emission into rsyncd.conf.

    Applies the following rules in order:
    - Packages where getattr(pkg.settings, 'hidden', False) is truthy are
      silently skipped (hidden is intentional, no warning).
    - Packages with an invalid module name (validate_module_name returns
      False) are skipped with a log.warning.
    - Packages with an empty, non-absolute, or control-char dst are skipped
      with a log.warning.
    - Among remaining packages, case-insensitive duplicate names are
      resolved by keeping the first occurrence in sorted order and skipping
      later duplicates with a log.warning naming both pkgids.

    Args:
        packages(Iterable): Iterable of package objects with attributes
            pkgid (str), name (str), and settings with hidden (bool),
            src (str), and dst (str).

    Return:
        visible(list): Packages that passed all checks, sorted by name
            (case-sensitive).
    """
    # Sort first to make dedup deterministic (first in sorted order wins).
    sorted_pkgs = sorted(packages, key=lambda p: p.name)

    candidates = []
    for pkg in sorted_pkgs:
        if getattr(pkg.settings, "hidden", False):
            continue

        if not validate_module_name(pkg.name):
            log.warning(
                "Package %r has invalid module name %r; skipping",
                pkg.pkgid,
                pkg.name,
            )
            continue

        dst = getattr(pkg.settings, "dst", "")
        if not dst:
            log.warning(
                "Package %r has empty dst; skipping",
                pkg.pkgid,
            )
            continue
        if not os.path.isabs(dst):
            log.warning(
                "Package %r has non-absolute dst %r; skipping",
                pkg.pkgid,
                dst,
            )
            continue
        if _has_control_chars(dst):
            log.warning(
                "Package %r has control characters in dst; skipping",
                pkg.pkgid,
            )
            continue

        candidates.append(pkg)

    # Deduplicate by case-insensitive name; first occurrence (already sorted) wins.
    seen: dict[str, str] = {}
    visible = []
    for pkg in candidates:
        lower_name = pkg.name.lower()
        if lower_name in seen:
            log.warning(
                "Package %r has duplicate module name (case-insensitive) with %r; skipping",
                pkg.pkgid,
                seen[lower_name],
            )
            continue
        seen[lower_name] = pkg.pkgid
        visible.append(pkg)

    return visible


def build_global_section(global_params: dict, secrets_file: str) -> str:
    """Build the global section of rsyncd.conf as a string.

    The section starts with CONF_HEADER, followed by one 'key = value' line
    per entry in global_params (insertion order preserved), then a blank
    line, then 'secrets file = <secrets_file>'.

    Args:
        global_params(dict): Ordered dict of global rsyncd parameters.
        secrets_file(str): Absolute path to the rsyncd.secrets file.

    Return:
        section(str): The global section text ending without a trailing
            newline (caller adds separating blank lines as needed).
    """
    lines = [CONF_HEADER]
    for key, value in global_params.items():
        lines.append(format_param(key, value))
    lines.append("")
    lines.append(format_param("secrets file", secrets_file))
    return "\n".join(lines)


def build_public_module(pkg: Any) -> str:
    """Build the public module block for a package.

    The block has no surrounding blank lines. Format:
        [<pkg.name>]
            path = <pkg.settings.dst>
            comment = from <sanitized pkg.settings.src>   (omitted if src is empty)

    Args:
        pkg: Package object with name (str) and settings.dst (str) and
            settings.src (str).

    Return:
        block(str): The module block text with no trailing newline.
    """
    lines = [f"[{pkg.name}]"]
    lines.append(f"    {format_param('path', pkg.settings.dst)}")
    src = getattr(pkg.settings, "src", "")
    if src:
        sanitized = sanitize_comment_value(src)
        lines.append(f"    {format_param('comment', f'from {sanitized}')}")
    return "\n".join(lines)


def build_private_module(pkg: Any, private_modules: dict) -> str:
    """Build the private module block for a package.

    The block has no surrounding blank lines. Format:
        [.<pkg.name>]
            path = <pkg.settings.dst>
            comment = private module for <pkg.name> without connection limits for authorized mirrors
            auth users = <auth_users>
            list = <list as true/false>
            lock file = <lock_file>

    Args:
        pkg: Package object with name (str) and settings.dst (str).
        private_modules(dict): Private module config with keys auth_users
            (str), list (bool), and lock_file (str).

    Return:
        block(str): The private module block text with no trailing newline.
    """
    comment = PRIVATE_COMMENT_TEMPLATE.format(name=pkg.name)
    lines = [
        f"[.{pkg.name}]",
        f"    {format_param('path', pkg.settings.dst)}",
        f"    {format_param('comment', comment)}",
        f"    {format_param('auth users', private_modules['auth_users'])}",
        f"    {format_param('list', private_modules['list'])}",
        f"    {format_param('lock file', private_modules['lock_file'])}",
    ]
    return "\n".join(lines)


def build_rsyncd_conf(packages: Iterable, config: dict) -> str:
    """Build the complete rsyncd.conf content as a string.

    Structure: global section, then for each visible package a blank line
    followed by the public module block; if private_modules is enabled,
    a blank line followed by the private module block. The document ends
    with exactly one trailing newline.

    Args:
        packages(Iterable): All packages; select_visible_packages filters
            and sorts them before use.
        config(dict): Validated config dict with keys 'global',
            'secrets_file', and 'private_modules'.

    Return:
        content(str): Complete rsyncd.conf content ending with a single
            newline character.
    """
    parts = [build_global_section(config["global"], config["secrets_file"])]

    visible = select_visible_packages(packages)
    private_enabled = config["private_modules"]["enabled"]

    for pkg in visible:
        parts.append("")
        parts.append(build_public_module(pkg))
        if private_enabled:
            parts.append("")
            parts.append(build_private_module(pkg, config["private_modules"]))

    return "\n".join(parts) + "\n"


def build_rsyncd_secrets(users: dict) -> str:
    """Build the complete rsyncd.secrets content as a string.

    One 'username:password\\n' line per entry in insertion order. Returns
    an empty string when users is empty. No header is emitted; rsyncd
    secrets files are plain user:pass lines.

    Args:
        users(dict): Mapping of username to password strings.

    Return:
        content(str): The secrets file content, or '' if users is empty.
    """
    if not users:
        return ""
    return "".join(f"{username}:{password}\n" for username, password in users.items())


# --- I/O layer ---


def write_file_atomic(path: Path, content: str, mode: int) -> bool:
    """Write content to path atomically, skipping the write if content is unchanged.

    If the target file already exists and its content equals the provided
    content, the file is not rewritten. However, if the existing file mode
    differs from mode, os.chmod is called to repair it. Returns False in
    that case.

    Otherwise, creates parent directories as needed, writes content to a
    temporary file in the same directory (created via tempfile.mkstemp at
    mode 0600 so secret content is never transiently world-readable), sets
    the target mode on the temp file, then atomically replaces the target.
    On any failure, the temp file is removed (best-effort) and the exception
    is re-raised. Returns True when a write occurred.

    Args:
        path(Path): Destination file path.
        content(str): UTF-8 text content to write.
        mode(int): Target file permission bits (e.g. 0o600 or 0o644).

    Return:
        written(bool): True if the file was (re)written, False if content
            was identical and only a possible mode repair was performed.
    """
    try:
        existing = path.read_text(encoding="utf-8")
    except OSError:
        existing = None

    if existing is not None and existing == content:
        current_mode = stat.S_IMODE(os.stat(path).st_mode)
        if current_mode != mode:
            os.chmod(path, mode)
        return False

    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp_name = tempfile.mkstemp(prefix=path.name + ".", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as fh:
            fh.write(content)
        os.chmod(tmp_name, mode)
        os.replace(tmp_name, path)
    except Exception:
        try:
            os.unlink(tmp_name)
        except OSError:
            pass
        raise
    return True


def regenerate_rsync_files(packages: Iterable, config: dict) -> None:
    """Write rsyncd.secrets and rsyncd.conf from the current package list and config.

    Secrets are written first because rsyncd.conf references the secrets
    path; the referenced file must be current before the conf lands so that
    a partial failure (e.g. disk full after writing secrets) leaves the
    previous conf intact rather than pointing at a stale secrets file.

    Args:
        packages(Iterable): Iterable of package objects passed to
            build_rsyncd_conf via select_visible_packages.
        config(dict): Validated config dict with keys 'users',
            'secrets_file', 'rsyncd_conf', 'global', and 'private_modules'.

    Return:
        None
    """
    secrets_text = build_rsyncd_secrets(config["users"])
    write_file_atomic(Path(config["secrets_file"]), secrets_text, 0o600)

    conf_text = build_rsyncd_conf(packages, config)
    write_file_atomic(Path(config["rsyncd_conf"]), conf_text, 0o644)


# --- Event / lifecycle layer ---


def handle_regenerate_event(*args: object, **kwargs: object) -> None:
    """Regenerate rsyncd.conf and rsyncd.secrets in response to a mirror event.

    Intended as a listener for MASTER.INIT.POST and MASTER.CONFIG_RELOAD.POST.
    The signature accepts arbitrary positional and keyword arguments because
    the event payload format is not finalized; all arguments are ignored.

    Reads mirror.packages and the rsync.json config path fresh at event time
    (never cached). The entire body runs under _generate_lock so concurrent
    event firings are serialized. All exceptions are caught and logged; the
    function never re-raises so a generation failure cannot disturb other
    listeners or the daemon, and previously generated files are left intact.

    Args:
        *args: Ignored event payload positional arguments.
        **kwargs: Ignored event payload keyword arguments.

    Return:
        None
    """
    with _generate_lock:
        try:
            path = resolve_rsync_config_path()
            config = load_rsync_config(path)
            check_config_permissions(path)
            packages = getattr(mirror, "packages", None)
            if packages is None:
                log.warning("mirror.packages is not available; skipping rsync file generation")
                return
            regenerate_rsync_files(list(packages.values()), config)
        except Exception as exc:
            log.error(
                "rsync-server plugin: failed to regenerate files: %s: %s",
                type(exc).__name__,
                exc,
            )


def setup() -> None:
    """Register handle_regenerate_event for daemon start and config reload events.

    Registers the listener for both MASTER.INIT.POST (daemon start) and
    MASTER.CONFIG_RELOAD.POST (config reload). This function performs no I/O;
    it only wires up listeners so it is safe to call in every process
    (including short-lived CLI runs).

    Args:
        (none)

    Return:
        None
    """
    mirror.event.on("MASTER.INIT.POST", handle_regenerate_event)
    mirror.event.on("MASTER.CONFIG_RELOAD.POST", handle_regenerate_event)


def plugin() -> "mirror.plugin.PluginRecord":
    """Return the mirror.py event plugin record for the rsync-server plugin.

    Uses a lazy import of mirror.plugin.event_plugin to match the pattern
    established by the mirror-plugin-echo example.

    Args:
        (none)

    Return:
        record(mirror.plugin.PluginRecord): Plugin record with name 'rsync-server',
            type 'event', and setup pointing to the setup function.
    """
    from mirror.plugin import event_plugin
    return event_plugin(name=NAME, setup=setup)
